/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Root {
	[k: string]: unknown;
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task".
 */
export interface Task {
	id: string;
	name: string;
	tip?: string;
	wikiLink: string;
	imageLink: string;
	displayItemId: number;
	verification?:
		| {
				method: Method;
				itemIds: number[];
				count: number;
		  }
		| {
				method: Method1;
				region: Region;
				difficulty: Difficulty;
		  }
		| {
				method: Method2;
				experience: {
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					attack?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					strength?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					defence?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					ranged?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					prayer?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					magic?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					runecraft?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					hitpoints?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					crafting?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					mining?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					smithing?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					fishing?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					cooking?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					firemaking?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					woodcutting?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					agility?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					herblore?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					thieving?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					fletching?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					slayer?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					farming?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					construction?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					hunter?: number;
					/**
					 * This interface was referenced by `Task`'s JSON-Schema
					 * via the `definition` "skill-experience".
					 */
					sailing?: number;
				};
				count: number;
		  };
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task-tier".
 */
export interface TaskTier {
	name: string;
	tasks: Task[];
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task-list".
 */
export interface TaskList {
	[k: string]: Task[];
}

export const enum Method {
	CollectionLog = 'collection-log'
}
export const enum Method1 {
	AchievementDiary = 'achievement-diary'
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "diary-region".
 */
export const enum Region {
	Ardougne = 'ardougne',
	Desert = 'desert',
	Falador = 'falador',
	Fremennik = 'fremennik',
	Kandarin = 'kandarin',
	Karamja = 'karamja',
	KourendAndKebos = 'kourend-and-kebos',
	LumbridgeAndDraynor = 'lumbridge-and-draynor',
	Morytania = 'morytania',
	Varrock = 'varrock',
	WesternProvinces = 'western-provinces',
	Wilderness = 'wilderness'
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "diary-difficulty".
 */
export const enum Difficulty {
	Easy = 'easy',
	Medium = 'medium',
	Hard = 'hard',
	Elite = 'elite'
}
export const enum Method2 {
	Skill = 'skill'
}
