/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Root {
	[k: string]: unknown;
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task".
 */
export interface Task {
	id: string;
	name: string;
	tip?: string;
	wikiLink: string;
	imageLink: string;
	displayItemId: number;
	verification?:
		| {
				method: Method;
				itemIds: number[];
				count: number;
		  }
		| {
				method: Method1;
				region: Region;
				difficulty: Difficulty;
		  };
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task-tier".
 */
export interface TaskTier {
	name: string;
	tasks: Task[];
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "task-list".
 */
export interface TaskList {
	[k: string]: Task[];
}

export const enum Method {
	CollectionLog = 'collection-log'
}
export const enum Method1 {
	AchievementDiary = 'achievement-diary'
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "diary-region".
 */
export const enum Region {
	Ardougne = 'ardougne',
	Desert = 'desert',
	Falador = 'falador',
	Fremennik = 'fremennik',
	Kandarin = 'kandarin',
	Karamja = 'karamja',
	KourendAndKebos = 'kourend-and-kebos',
	LumbridgeAndDraynor = 'lumbridge-and-draynor',
	Morytania = 'morytania',
	Varrock = 'varrock',
	WesternProvinces = 'western-provinces',
	Wilderness = 'wilderness'
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "diary-difficulty".
 */
export const enum Difficulty {
	Easy = 'easy',
	Medium = 'medium',
	Hard = 'hard',
	Elite = 'elite'
}
